### ISSUE TITLE
X- Issues 

### ISSUE THREAD

**Issue by priyalviroja** [ss250294/NGO-portal-website#1]
1) Why public ???
- server side scripts should not be public.

2) Why not secure code implementation ??? 
- Had look at your php code and it looks vulnerable to SQLi, XSS, Authentication and Authorization and logical bugs

Hackers can easily tricks SQL queries to get their dirty hands on server.

**Comment by Vijay13** [comment]
Hello Priyal,

Thank you very much for your concern and suggestions. I assure you that
they are really helpful to us. We will soon learn and implement the
security to our website.

Your advises are most welcome.

Regards,
Vijay
